name: home-ops

# Apps
include:
  - core/traefik/traefik.yml
  - apps/adminer/adminer.yml
  - apps/website-aaronsoft/website-aaronsoft.yml
  - apps/website-get-orga-niced/website-get-orga-niced.yml

networks:
  # Public traffic (Traefik <-> Apps)
  traefik-public:
    name: traefik-public
    driver: bridge

  # Secured Socket (Traefik <-> Socket Proxy)
  socket-internal:
    name: socket-internal
    internal: true

  # Database traffic (Apps <-> DBs) - Not exposed to Traefik
  db-internal:
    name: db-internal
    internal: true