include:
  - core/traefik/docker-compose.yml
  - apps/adminer/docker-compose.yml
  - apps/website-aaronsoft/docker-compose.yml
  - apps/website-get-orga-niced/docker-compose.yml
  # Add other apps here as you build them